# Generated by Django 6.0.4 on 2026-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_type', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(help_text='Separate skills with commas', max_length=255)),
                ('upstream_dependencies', models.CharField(blank=True, max_length=255)),
                ('downstream_dependencies', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('repository', models.URLField(blank=True)),
            ],
        ),
    ]
